name: deploy to server

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            # add php & composer
            - name: Set up PHP & Composer
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  tools: composer:v2
            # # composer install
            - name: Composer install
              run: composer install
            # # add nodejs & npm
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
            # # npm install
            - name: NPM install
              run: npm install -f
            # # npm build
            - name: NPM build
              run: npm run build
            # deploy to server without vendor & node_modules folder
            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.SFTP_HOST }}
                  port: 21
                  username: ${{ secrets.SFTP_USER }}
                  password: ${{ secrets.SFTP_PASS }}
                  server-dir: dev.madrasatulhera.com/
                  exclude: |
                      **/.git*
                      **/.git*/**
                      **/node_modules/**
                  # **/vendor/**
            # send notification to telegram
            - name: Send notification to Telegram
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
